### ISSUE TITLE
how can I get the new params file？

### ISSUE THREAD

**Issue by fhowen** [Leliana/WhatsThis#1]
Hi，I am using your app ,but I want to try other net-type and params.So.how can I get the new params?
Many Thanks.

**Comment by antinucleon** [comment]
You can replace `params`, `symbol.json` and `mean.json` with model trained by MXNet directly. Note currently we only support numerical mean value.

```
 ----res
     |
     -----raw
          |
          ------params
          |
          ------symbol.json
          |
          ------synset.txt
          |
          ------mean.json
```
